imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    redis_dns: redis://localhost

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: [192.168.56.101,192.168.56.102]
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        #handler_id:  session.handler.native_file
        handler_id:  snc_redis.session.handler
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'form/widgets.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        #charset:  utf8mb4
        #default_table_options:
            #charset: utf8mb4
            #collate: utf8mb4_unicode_ci
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        schema_filter: ~^(?!t_)~
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        # enable metadata caching
        metadata_cache_driver:
            type: service
            id: snc_redis.doctrine
        # enable query caching
        query_cache_driver:
            type: service
            id: snc_redis.doctrine
        # enable results caching
        result_cache_driver:
            type: service
            id: snc_redis.doctrine

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUser Bundle
fos_user:
    db_driver: orm
    firewall_name: secured_area
    user_class: \AppBundle\Entity\User

# Database Migrations
doctrine_migrations:
  dir_name: "%kernel.root_dir%/DoctrineMigrations"
  namespace: Application\Migrations
  table_name: migration_versions
  name: Application Migrations


# Redis (http://olegpuzanov.com/2015/02/01/using-redis-for-doctrine-caching-in-symfony2/)
# https://www.ekreative.com/blog/three-symfony2-database-optimisation-tips-to-implement-today
snc_redis:
    # configure predis as client
    clients:
        default:
            type: predis
            alias: default
            dsn: '%redis_dns%'
        doctrine:
            type: predis
            alias: doctrine
            dsn: '%redis_dns%'
        session:
             type: predis
             alias: session
             dsn: '%redis_dns%'
    # configure doctrine caching
    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default          # the name of your entity_manager connection
            document_manager: default        # the name of your document_manager connection
        result_cache:
            client: doctrine
            entity_manager: [default]  # you may specify multiple entity_managers
        query_cache:
            client: doctrine
            entity_manager: default
    # configure session caching
    session:
        client: session
        ttl: 1200

#FOSHttpCache Bundle
fos_http_cache:
    proxy_client:
        symfony:
            servers: 127.0.0.1
            base_url: '%fos_http_cache_base_url%'
    user_context:
        enabled: true
        role_provider: true
    cache_control:
        defaults:
            overwrite: false
        rules:
            -
                match:
                    #path: ^/site$ # site homepage
                    attributes:
                        _route: site_homepage
                headers:
                    overwrite: true
                    reverse_proxy_ttl: 610
                    cache_control:
                        public: true
                        max_age: 510
                    vary: My-Custom-Blog-Header
    invalidation:
        enabled: true
        rules:
            -
                match:
                    attributes:
                        _route: "post.edit|post.create|post.delete"
                routes:
                    site_homepage: ~

# GitHub OAuth
app:
    github_oauth:
        client_id: '03d687dee778a74bda17'
        client_secret: '6e46fcd7bd01d6bfb8dfff1c3045484c6816f42b'