imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata_classification.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    redis_dns: redis://localhost

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: [192.168.56.101,192.168.56.102]
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        #handler_id:  session.handler.native_file
        handler_id:  snc_redis.session.handler
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - 'SonataMediaBundle:Form:media_widgets.html.twig'
        - 'form/widgets.html.twig'
    paths:
        '%kernel.root_dir%/../src/AppBundle/Resources/views': AppBundle

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        #charset:  utf8mb4
        #default_table_options:
            #charset: utf8mb4
            #collate: utf8mb4_unicode_ci
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        schema_filter: ~^(?!t_)~
        # https://gist.github.com/romansklenar/525030/38a0dd6a70e58f39e964ec53c746457dd37a5f58
        # http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#custom-mapping-types
        # http://stackoverflow.com/questions/4837589/doctrine-custom-data-type
        types:
            coordinates: AppBundle\ORM\Type\CoordinatesType
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"

        entity_managers:
            default:
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~
                filters:
                  - { name: 'post_by_author_filter', class: AppBundle\ORM\Filter\PostByAuthorFilter, enabled: false }
                # enable metadata caching
                metadata_cache_driver:
                    type: service
                    id: snc_redis.doctrine
                # enable query caching
                query_cache_driver:
                    type: service
                    id: snc_redis.doctrine
                # enable results caching
                result_cache_driver:
                    type: service
                    id: snc_redis.doctrine

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUser Bundle
fos_user:
    db_driver: orm
    firewall_name: secured_area
    user_class: \AppBundle\Entity\User

# Database Migrations
doctrine_migrations:
  dir_name: "%kernel.root_dir%/DoctrineMigrations"
  namespace: Application\Migrations
  table_name: migration_versions
  name: Application Migrations


# Redis (http://olegpuzanov.com/2015/02/01/using-redis-for-doctrine-caching-in-symfony2/)
# https://www.ekreative.com/blog/three-symfony2-database-optimisation-tips-to-implement-today
snc_redis:
    # configure predis as client
    clients:
        default:
            type: predis
            alias: default
            dsn: '%redis_dns%'
        doctrine:
            type: predis
            alias: doctrine
            dsn: '%redis_dns%'
        session:
             type: predis
             alias: session
             dsn: '%redis_dns%'
    # configure doctrine caching
    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default          # the name of your entity_manager connection
            document_manager: default        # the name of your document_manager connection
        result_cache:
            client: doctrine
            entity_manager: [default]  # you may specify multiple entity_managers
        query_cache:
            client: doctrine
            entity_manager: default
    # configure session caching
    session:
        client: session
        ttl: 1200

#FOSHttpCache Bundle
fos_http_cache:
    proxy_client:
        symfony:
            servers: 127.0.0.1
            base_url: '%fos_http_cache_base_url%'
    user_context:
        enabled: true
        role_provider: true
    cache_control:
        defaults:
            overwrite: false
        rules:
            -
                match:
                    #path: ^/site$ # site homepage
                    attributes:
                        _route: site_homepage
                headers:
                    overwrite: true
                    reverse_proxy_ttl: 610
                    cache_control:
                        public: true
                        max_age: 510
                    vary: My-Custom-Blog-Header
    invalidation:
        enabled: true
        rules:
            -
                match:
                    attributes:
                        _route: "post.edit|post.create|post.delete"
                routes:
                    site_homepage: ~

# Sonata Core
sonata_core:
    flashmessage:
        success:
            types:
                - { type: post.success, domain: AppBundle }

# Sonata Block
sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text: ~
        sonata.block.service.template: ~
        sonata.media.block.media: ~
        sonata.media.block.gallery: ~
        sonata.media.block.feature_media: ~

# Sonata Media Bundle
sonata_media:
    # if you don't use default namespace configuration
    #class:
        #media: Application\Sonata\MediaBundle\Entity\Media
        #gallery: Application\Sonata\MediaBundle\Entity\Gallery
        #gallery_has_media: Application\Sonata\MediaBundle\Entity\Media\GalleryHasMedia
    providers:
        image:
            resizer: sonata.media.resizer.square
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                preview: { width: 100, quality: 100}
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        post:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                preview: { width: 100, quality: 100}
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false

# GitHub OAuth
app:
    github_oauth:
        client_id: '03d687dee778a74bda17'
        client_secret: '6e46fcd7bd01d6bfb8dfff1c3045484c6816f42b'

    dashboard:
      modules:
        a:
          label: A
          icon: 'fa fa-code-fork'
          actions: ~
          children:
            a1:
              label: A1
              icon: ~
              actions:
                - { label: 'View', route: 'a1.route', icon:'fa fa-code-fork' }
            a2:
              label: A2
              icon: ~
              actions:
                - { label: 'View 2', route: 'a2.route', icon:'fa fa-code-fork' }

        blog:
          label: Blog
          icon: 'fa fa-code-fork fa-fw'
          actions:
            - { label: 'List', route: 'homepage', icon:'fa fa-code-fork' }
            - { label: 'New Post', route: 'post.create', icon: 'fa fa-plus' }
          children: ~

        media:
          label: Media
          icon: 'fa fa-code-fork fa-fw'
          actions: ~
          children:
            post:
              label: Post Media
              icon: ~
              actions:
                - { label: List, route: 'media.post.list', icon: 'fa fa-code-fork' }
                - { label: Add, route: 'media.post.add', icon: 'fa fa-plus' }
            article:
              label: Article Media
              icon: ~
              actions:
                - { label: List, route: 'media.article.list', icon:'fa fa-code-fork' }
                - { label: Add, route: 'media.article.add', icon: 'fa fa-plus' }

        gallery:
          label: Gallery
          icon: 'fa fa-code-fork fa-fw'
          actions:
            - { label: List, route: 'media.gallery.list', icon:'fa fa-code-fork' }
            - { label: New, route: 'media.gallery.create', icon: 'fa fa-plus' }
          children: ~

knp_menu:
    twig:
        template: 'AppBundle::menu.html.twig'