# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  # http://php-and-symfony.matthiasnoback.nl/2014/05/inject-a-repository-instead-of-an-entity-manager/
  app.post_repository:
      class: AppBundle\Entity\PostRepository
      factory: ['@doctrine.orm.entity_manager', getRepository]
      arguments:
          - AppBundle\Entity\Post
      tags:
          - { name: 'repository.redis.default' }

  app.twig.extension:
      class: AppBundle\Twig\AppExtension
      tags:
          - { name: twig.extension }


  app.form.type.coordinate:
      class: AppBundle\Form\Type\CoordinateType
      arguments: ['@ivory_google_map.map']
      tags:
          - { name: form.type, alias: coordinate }

  app.form.type.post:
        class: AppBundle\Form\Type\PostType
        arguments: ['@sonata.media.manager.media']
        tags:
            - { name: form.type, alias: post }

  app.post.listener:
      class: AppBundle\EventListener\PostEventListener
      arguments: ['@slugify']
      tags:
        - { name: doctrine.event_listener, event: preUpdate }
        - { name: doctrine.event_listener, event: prePersist }


  acme.hello.menu.voter.request:
          class: AppBundle\Menu\RequestVoter
          arguments: ['@request_stack']
          tags:
            - { name: knp_menu.voter }


  app.github.authentication_listener:
      class: AppBundle\Security\GitHub\AuthenticationListener
      parent: security.authentication.listener.abstract
      abstract: true
      public: false

  app.github.authentication_provider:
      class: AppBundle\Security\GitHub\AuthenticationProvider
      public: false

  app.github.authentication.entry_point.oauth:
      class: AppBundle\Security\Http\EntryPoint\OAuthEntryPoint
      public: false
      abstract: true
      arguments: ['@app.github.authorize.redirect_response']

  app.github.authorize.redirect_response:
      class: AppBundle\Security\GitHub\AuthorizeRedirectResponse
      arguments: ['@?request_stack', '@security.http_utils', '@http_kernel']

  app.github.user_provder:
      class: AppBundle\Security\GitHub\UserProvider
      arguments: ['@fos_user.user_manager']

  app.security.access.valid_user:
      class: AppBundle\EventListener\ValidUserListener
      arguments: ['@annotation_reader', '@router', '@session', '@security.token_storage', '@validator']
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController}

  app.security.access.api:
      class: AppBundle\EventListener\ApiCustomCookieListener
      tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest}